modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/Raxdiam/DawnConfig/issues/"
displayURL = "https://github.com/Raxdiam/DawnConfig/"
logoFile = "assets/dawn-config/icon.png"
authors = ["shedaniel", "Raxdiam"]
license = "GNU GPL 3.0"

[[mods]]
modId = "dawn_config"
version = "${version}"
displayName = "Dawn Config API"
description = '''
A fork of Cloth Config API using Night Config as the serializer.
'''

[[dependencies.dawn_config]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"
